# Generated by Django 3.2.6 on 2021-08-13 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210813_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='FkeyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='human',
            name='fField',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='store.fkeymodel'),
            preserve_default=False,
        ),
    ]
