# Generated by Django 3.2.6 on 2021-08-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210813_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
