# Generated by Django 3.2.6 on 2021-08-14 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_human_dateadded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('evolved', models.BooleanField(default=False)),
                ('fField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.fkeymodel')),
                ('isHuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.human')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
