# Generated by Django 3.2.6 on 2021-08-14 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_monkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='evolved',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.monkey'),
            preserve_default=False,
        ),
    ]
