# Generated by Django 3.2.6 on 2021-08-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratings',
            options={'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterField(
            model_name='ratings',
            name='star',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
