# Generated by Django 3.2.6 on 2021-08-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_human_evolved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monkey',
            options={},
        ),
        migrations.RemoveField(
            model_name='monkey',
            name='age',
        ),
        migrations.RemoveField(
            model_name='monkey',
            name='dateAdded',
        ),
        migrations.RemoveField(
            model_name='monkey',
            name='fField',
        ),
        migrations.RemoveField(
            model_name='monkey',
            name='name',
        ),
    ]
