# Generated by Django 3.2.6 on 2021-08-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210814_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='monkey',
            name='detail',
            field=models.CharField(default='e', max_length=10),
            preserve_default=False,
        ),
    ]
