# Generated by Django 3.2.6 on 2021-08-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_monkey_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='fField',
        ),
        migrations.RemoveField(
            model_name='monkey',
            name='isHuman',
        ),
        migrations.DeleteModel(
            name='FkeyModel',
        ),
        migrations.DeleteModel(
            name='Human',
        ),
        migrations.DeleteModel(
            name='Monkey',
        ),
    ]
